// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pesumnjxwmglnnrbuewg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlc3Vtbmp4d21nbG5ucmJ1ZXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjA0MDMsImV4cCI6MjA2MDczNjQwM30.ZYMYyyLXwcneOBOJRGo-WYKn9zkyERUTsDVSIGHSvfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);